### ISSUE TITLE
SMN's Ruin IV stacks function is not working properly.

### ISSUE THREAD

**Issue by ShadyWhite** [Zeffuro/ZeffUI#10]
Test by me in CN client & @MaikoTan in Intl client(JA).

**Comment by Zeffuro** [comment]
Will try to have a look this evening. I know it works for EN but haven't tested that in CN (don't think I have access to that version) but I can certainly check out the JA version and see if something similar is wrong

**Comment by Zeffuro** [comment]
Ok I made some changes, can you and https://github.com/MaikoTan try it again?
I think the regex was too strict. For me it works in Japanese now and I suspect it will work for Chinese too but I don't have the Chinese client.

**Comment by ShadyWhite** [comment]
> Ok I made some changes, can you and @MaikoTan try it again?
> I think the regex was too strict. For me it works in Japanese now and I suspect it will work for Chinese too but I don't have the Chinese client.

I just tested it in CN client.The player name rule for CN client is different from Intl client. In CN client both English name and Chinese name can be used, with a maximum of 6 characters. This results in the English name matching the regex, but the Chinese name not matching the regex.BTW,@MaikoTan tested it in Intl client (JA) and it works fine already.
![image](https://user-images.githubusercontent.com/44015352/103498485-ec778100-4e7f-11eb-8f1a-9ec60276e479.png)
![image](https://user-images.githubusercontent.com/44015352/103498537-18930200-4e80-11eb-8e30-c0ce5aa0afac.png)

**Comment by MaikoTan** [comment]
![image](https://user-images.githubusercontent.com/19927330/103499084-d36fcf80-4e81-11eb-9071-4fd4f54065c0.png)

So I think this should be changed as `(?<player>[^:]+)`, just like the target name matching regex.

**Comment by Zeffuro** [comment]
Well RIP, that throws regex speed/efficiency out the window.
I've changed it, could you try again?

**Comment by ShadyWhite** [comment]
> Well RIP, that throws regex speed/efficiency out the window.
> I've changed it, could you try again?

Works fine for me now.
