### ISSUE TITLE
Feature Request: Add Abilities to Party Anchor

### ISSUE THREAD

**Issue by Akurosia** [Zeffuro/ZeffUI#20]
It would be nice to edit/add some skills in the party anchor.
E.g. for Bluemage i would like to see who can still rezzing and other stuff

**Comment by Zeffuro** [comment]
Should be possible to implement, just need to think about how to properly do it, will see if I have time to implement and test.

**Comment by natyusha** [comment]
This would be great as there are several skills that would make a lot of sense to be in the party anchor like Divine Veil, Temperance, Asylum, Collective Unconscious and more.

**Comment by Zeffuro** [comment]
This actually has been added in a limited capacity, when adding abilities to custom cooldowns set the type to party.

It might be slightly buggy for some abilities but patches are always welcome :)

**Comment by natyusha** [comment]
Thanks for the heads up! Should be able to completely replace specialspelltimers with this now.

Also, Is it possible to right justify the party anchor? Some setups would look a bit better if so.
![Capture](https://user-images.githubusercontent.com/985941/129345160-5f706c76-15af-42c4-af44-3c62f5c75f0e.PNG)

**Comment by Zeffuro** [comment]
It's an issue I've been looking into but I haven't found a good way to fix it yet outside of doing every image with absolute positioning in CSS, if you or anyone else has any idea or any patch to make it work like I intended let me know (I really want it to justify right too).

**Comment by natyusha** [comment]
You should be able to use `flex-direction: row-reverse;` on the ability-box class to achieve this.

**Comment by Zeffuro** [comment]
> You should be able to use `flex-direction: row-reverse;` on the ability-box class to achieve this.

That looks EXACTLY what I needed.
I just implemented this and at first glance it works for all the other frames but I haven't had time to hop into a trial / group content yet so please let me know if this fully works for party too.

**Comment by Zeffuro** [comment]
Awesome, then it looks like this issue is fully finished, thanks for all the input!
