### ISSUE TITLE
How to add abilities to custom cooldowns

### ISSUE THREAD

**Issue by gamer4eg** [Zeffuro/ZeffUI#24]
I immediately apologize for the fact that the text was generated by a google translator.
Can't add ability to custom cooldowns.
I search by name, press the save button.
I wish to save and reload the overlay.
Custom cooldown anchor still empty = (
![image](https://user-images.githubusercontent.com/23147230/125616902-6fdeae34-f3e9-4447-b44c-e7268e9a73d9.png)
![image](https://user-images.githubusercontent.com/23147230/125616927-1211f10f-d65c-4e30-a7bf-76486e1b10b8.png)

**Comment by Zeffuro** [comment]
Don't worry about using Google Translate, your question is clear to me!

I want to doublecheck if anything happened to the settings.
Could you export the JSON and post the contents here?

![image](https://user-images.githubusercontent.com/4972345/125617473-28329894-67c8-453c-95a1-7c7a521de3a6.png)

**Comment by gamer4eg** [comment]
`{
  "skin": "material-dark",
  "language": "en",
  "font": "Arial",
  "includealliance": false,
  "partyorder": [
    "PLD",
    "GLA",
    "WAR",
    "MRD",
    "DRK",
    "GNB",
    "WHM",
    "CNJ",
    "SCH",
    "AST",
    "MNK",
    "PGL",
    "DRG",
    "LNC",
    "NIN",
    "ROG",
    "SAM",
    "BRD",
    "ARC",
    "MCH",
    "DNC",
    "BLM",
    "THM",
    "SMN",
    "ACN",
    "RDM",
    "BLU"
  ],
  "override": {
    "enabled": false,
    "abilities": [
      {
        "id": 7531,
        "name": "Rampart",
        "name_cn": "铁壁",
        "name_de": "Schutzwall",
        "name_en": "Rampart",
        "name_fr": "Rempart",
        "name_jp": "ランパート",
        "name_kr": "철벽 방어",
        "enabled": true,
        "tts": true,
        "ttstype": 0,
        "job": "Tank",
        "level": 8,
        "duration": 20,
        "cooldown": 90,
        "type": "Mitigation",
        "icon": "https://xivapi.com/i/000000/000801.png",
        "color": "--filter-light-blue",
        "order": 0
      }
    ]
  },
  "debug": {
    "enabled": false
  },
  "general": {
    "usewebtts": false,
    "ttsearly": "5"
  },
  "healthbar": {
    "enabled": true,
    "hideoutofcombat": false,
    "textenabled": true,
    "color": "--filter-dark-green",
    "scale": "2.5",
    "rotation": "0",
    "x": 197,
    "y": 552,
    "align": "left",
    "font": "Arial"
  },
  "manabar": {
    "enabled": false,
    "hideoutofcombat": false,
    "textenabled": true,
    "jobthresholdsenabled": true,
    "color": "--filter-light-pink",
    "lowcolor": "--filter-dark-red",
    "medcolor": "--filter-light-blue",
    "scale": "1",
    "rotation": "0",
    "x": 30,
    "y": 232,
    "align": "left",
    "font": "Arial",
    "BLM": {
      "low": 2399,
      "med": 3999
    },
    "PLD": {
      "low": 3600,
      "med": 9400
    },
    "DRK": {
      "low": 2999,
      "med": 5999
    }
  },
  "mpticker": {
    "enabled": false,
    "hideoutofcombat": false,
    "color": "--filter-grey",
    "scale": "1",
    "rotation": "0",
    "x": 184,
    "y": 220,
    "specificjobsenabled": true,
    "specificjobs": [
      "BLM"
    ]
  },
  "dotticker": {
    "enabled": false,
    "hideoutofcombat": false,
    "color": "--filter-grey",
    "scale": "1",
    "rotation": "0",
    "x": 181,
    "y": 280,
    "specificjobsenabled": true,
    "specificjobs": [
      "BRD"
    ]
  },
  "hotticker": {
    "enabled": false,
    "hideoutofcombat": false,
    "color": "--filter-grey",
    "scale": "1",
    "rotation": "0",
    "x": 4,
    "y": 347,
    "specificjobsenabled": true,
    "specificjobs": [
      "AST",
      "SCH",
      "MKN",
      "WHM"
    ]
  },
  "timerbar": {
    "enabled": false,
    "textenabled": true,
    "color": "--filter-dark-red",
    "scale": "1",
    "rotation": "0",
    "x": 30,
    "y": 200,
    "font": "Arial"
  },
  "dottimerbar": {
    "enabled": false,
    "hideoutofcombat": false,
    "hidewhendroppedoff": false,
    "textenabled": false,
    "ttsenabled": false,
    "imageenabled": true,
    "multidotenabled": true,
    "growdirection": "1",
    "padding": "20",
    "scale": "1",
    "rotation": "0",
    "x": 19,
    "y": 41,
    "font": "Arial"
  },
  "bufftimerbar": {
    "enabled": false,
    "hideoutofcombat": false,
    "hidewhendroppedoff": false,
    "textenabled": false,
    "ttsenabled": false,
    "imageenabled": true,
    "growdirection": "1",
    "padding": "20",
    "scale": "1",
    "rotation": "0",
    "x": 30,
    "y": 100,
    "font": "Arial"
  },
  "stacksbar": {
    "enabled": false,
    "hideoutofcombat": false,
    "color": "--filter-bright-red",
    "scale": "1",
    "x": 30,
    "y": 170
  },
  "raidbuffs": {
    "enabled": true,
    "ttsenabled": false,
    "hideoutofcombat": false,
    "hidewhensolo": false,
    "orderbypartymember": true,
    "alwaysshow": true,
    "growleft": false,
    "columns": "8",
    "padding": "0",
    "scale": "1",
    "x": 589,
    "y": 202,
    "font": "Arial",
    "durationoutline": true,
    "durationbold": true,
    "cooldownoutline": true,
    "cooldownbold": true,
    "durationcolor": "#FFA500",
    "cooldowncolor": "#FFFFFF",
    "durationoutlinecolor": "#000000",
    "cooldownoutlinecolor": "#000000"
  },
  "mitigation": {
    "enabled": true,
    "ttsenabled": false,
    "hideoutofcombat": false,
    "hidewhensolo": false,
    "alwaysshow": true,
    "growleft": false,
    "columns": "8",
    "padding": "0",
    "scale": "1",
    "x": 215,
    "y": 463,
    "font": "Arial",
    "durationoutline": true,
    "durationbold": true,
    "cooldownoutline": true,
    "cooldownbold": true,
    "durationcolor": "#FFA500",
    "cooldowncolor": "#FFFFFF",
    "durationoutlinecolor": "#000000",
    "cooldownoutlinecolor": "#000000"
  },
  "party": {
    "enabled": true,
    "ttsenabled": false,
    "hideoutofcombat": false,
    "hidewhensolo": false,
    "alwaysshow": true,
    "growleft": false,
    "padding": "0",
    "scale": "0.8",
    "x": 569,
    "y": 367,
    "font": "Arial",
    "durationoutline": true,
    "durationbold": true,
    "cooldownoutline": true,
    "cooldownbold": true,
    "durationcolor": "#FFA500",
    "cooldowncolor": "#FFFFFF",
    "durationoutlinecolor": "#000000",
    "cooldownoutlinecolor": "#000000"
  },
  "customcd": {
    "abilities": [
      {
        "id": "20",
        "name": "Fight or Flight",
        "name_cn": "战逃反应",
        "name_de": "Verwegenheit",
        "name_en": "Fight or Flight",
        "name_fr": "Combat acharné",
        "name_kr": "임전무퇴",
        "enabled": true,
        "tts": true,
        "ttstype": "0",
        "job": "PLD",
        "duration": "25",
        "cooldown": "60",
        "type": "CustomCooldown",
        "icon": "https://xivapi.com/i/000000/000166.png",
        "color": "--filter-light-blue",
        "order": "0",
        "extra": {
          "charges": "0"
        }
      }
    ],
    "enabled": true,
    "ttsenabled": false,
    "hideoutofcombat": false,
    "hidewhensolo": false,
    "alwaysshow": true,
    "growleft": false,
    "padding": "0",
    "scale": "1",
    "columns": "8",
    "x": 396,
    "y": 292,
    "font": "Arial",
    "durationoutline": true,
    "durationbold": true,
    "cooldownoutline": true,
    "cooldownbold": true,
    "durationcolor": "#FFA500",
    "cooldowncolor": "#FFFFFF",
    "durationoutlinecolor": "#000000",
    "cooldownoutlinecolor": "#000000"
  }
}`

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/125618376-7d6b5ad7-9391-4d08-834d-301815c33935.png)
Just in case - a screenshot of the plugins

**Comment by Zeffuro** [comment]
Thanks for the information, I have found the bug and I have pushed a fix.
in 5 minutes from now please delete the ability and add it again.

The issue was caused by a bug that dropped the level property after you change the job (because the ability is originally from Gladiator).

Let me know if it works for you but in my test case it seems to work now!

**Comment by gamer4eg** [comment]
It's work! THX!
