### ISSUE TITLE
Adjusting the 'Scale' of the Buff Tracker.

### ISSUE THREAD

**Issue by PsiloCA** [Zeffuro/ZeffUI#26]
I'm referring specifically to the buff tracker for the summoner Ruin IV stacks but I'm sure this applies to other jobs in the game. Id like to adjust the scale or length/height of the Ruin IV Tracker as well as the buff tracker as a whole just like you can do with the cooldown tracker. I looked around to see if there was a solution before making this ticket and I was not successful. I did see a comment from 4 days ago on the 'how to' video on YouTube. https://www.youtube.com/watch?v=klKDNfzPWSI. A response suggested the answer could be found within the Github however I could not find it and do not wish to install the entire ZeffUI at this time. I only wish to utilize the BuffTracker. TY for your good works my friend!

**Comment by Zeffuro** [comment]
Hmm you do need to install the whole ZeffUI (but you can disable the modules you don't want to use) for this version to work. The only other way to only have the Ruin IV tracker from Triggernometry scaled you'll need to adjust the height and width of every image action (I only show one as example) and also change the ${var:R4TrackerX} + 18 in every one of them to ${var:R4TrackerX} + 36

https://user-images.githubusercontent.com/4972345/127674016-fedd90f8-5860-470c-8a2f-98d7b71bdd69.mp4
