### ISSUE TITLE
Add in Expressway as a font

### ISSUE THREAD

**Issue by Zeffuro** [Zeffuro/ZeffUI#30]

**Comment by Zeffuro** [comment]
The license does not allow me to embed the font without me buying it and even after that I'd have to obfuscate the actual font so others can't easily get it apparently which makes that hard since this is all in a Github Repo.
https://typodermicfonts.com/license/

I was able to add the font in as a check but users that want to use the font will have to download the font from: https://www.dafont.com/expressway.font

After that just restart ACT and it should be in the font list.

**Comment by natyusha** [comment]
Allowing people to type in the exact name of local fonts that they would like to use would be quite nice if you are already doing something similar with this single font.

For example, if I wanted to use FFXIV's native font I would type in "AxisLatinPro-Regular" in the font selection and it would display that for the font if I had it on my PC with a simple fallback to whatever the default is if it isn't present.

**Comment by Zeffuro** [comment]
Yeah I've thought about that, I'm just kind of stuck on how to neatly get it into the settings without breaking the other font settings.

**Comment by Zeffuro** [comment]
Found a smart way to add it in, should work now.
