### ISSUE TITLE
[Suggestion] Party List sorting per role

### ISSUE THREAD

**Issue by Vayhyr** [Zeffuro/ZeffUI#34]
Kinda like the in-game version where you can sort roles based on the role you are. 
![party list sorting per role](https://i.imgur.com/viZl27c.png)

**Comment by Zeffuro** [comment]
It's possible but will take some more sophisticated work, will see when I have time to tackle this.

**Comment by Zeffuro** [comment]
I've implemented the feature (in the simplest way possible for now) so you'll have to set all the jobs for each role but it should work fine!
