### ISSUE TITLE
HP/MP Bar rotation

### ISSUE THREAD

**Issue by ChadRD** [Zeffuro/ZeffUI#41]
I'm not sure if I'm missing a setting or if this isn't working, but when trying to rotate the HP/MP bars to vertical in settings, they don't accept any input and stay at their default orientation.

I would like to move them to be similar to the UI option in [this](https://i.imgur.com/NrDA39r.png) screenshot, but with the added functionality and customization of your UI - plus your bars are a lot cleaner.

**Comment by Zeffuro** [comment]
Looks like this feature broke somewhere, I'll have a look and see if I can fix it.
