### ISSUE TITLE
[Bug]: Scholar's 'Sacred Soil' shows 90s cooldown instead of 30s.

### ISSUE THREAD

**Issue by g0shu** [Zeffuro/ZeffUI#44]
### What are you trying to do?

Honestly I'd say it's not worth tracking at all with cooldown that short. Summon seraph might be a better default option with its 120s cooldown.

### What is the expected behaviour?

.

### What actually happened?

.

### FFXIV Update

- [X] I have confirmed that I have the latest version of Ravahn's FFXIV_ACT_Plugin, ngld's OverlayPlugin and cactbot (for the memory reading) are up to date.

**Comment by Zeffuro** [comment]
You can turn it off in the override section it you don't want to see it, I only added it in because loads of healers wanted it. You can add in Summon Seraph in the Custom Cooldown section and set Type to Party.

Pushed fix too :)
