### ISSUE TITLE
[Help wanted]: Put CD Icons in the background

### ISSUE THREAD

**Issue by ExtraThicc1993** [Zeffuro/ZeffUI#49]
### What's the issue?

Hello there!

I have recently started using ZeffUi and absolutely love it. I have set up a few custom cooldowns above my healthbar near the center of my screen. My question is: can you put these icons in the background so that they are behind in-game menus like retainers and the mini-cactpot? I know you can disable them outside of combat but is there a way to make them have less of a priority over in-game menus?

Thanks in advance!

### FFXIV Update

- [X] I have confirmed that I have the latest version of Ravahn's FFXIV_ACT_Plugin, ngld's OverlayPlugin and cactbot (for the memory reading) are up to date.

**Comment by Zeffuro** [comment]
I don't have access to ingame stuff to hide it behind but the best you can do is set a hotkey to all the overlays you use in ACT

![image](https://user-images.githubusercontent.com/4972345/131225489-ad020437-769a-42f1-9f21-662943fd915b.png)

**Comment by ExtraThicc1993** [comment]
Ill try that, thanks!
