### ISSUE TITLE
[Suggestion]: Add separate options for vertical and horizontal padding for the "Party Cooldowns" element

### ISSUE THREAD

**Issue by ChazHanda** [Zeffuro/ZeffUI#51]
### What's your suggestion?

I'm aiming for a small Party Cooldown display, but to align a scaled-down display with the in-game party list I need to add vertical padding. The problem is that when I add padding, the cooldown icons also get padded horizontally when I would prefer for them to be close together like the default buff/debuff icons. 

My end goal is to have them spaced similarly to how buffs show, but also aligned with the party list.
Example of buff spacing 
![Buff Spacing](https://puu.sh/IcOQu/66e8952575.png)

This screenshot has the Party Cooldowns close to each other horizontally, but it doesn't line up vertically.
![Low Padding](https://puu.sh/IcOYR/89d8804516.png)

This screenshot has the Party Cooldowns more aligned with the party list, but the icons are spaced out horizontally.
![High Padding](https://puu.sh/IcP04/6dcdf76237.png)

Great overlay! I haven't had anything else bother me.

**Comment by Zeffuro** [comment]
Haven't had the time yet to do this but you can work around it with custom CSS at this point

```
div[id^="party-row-"] {
margin-bottom: 10px;
}
```

**Comment by ChazHanda** [comment]
Thank you! I played around with the numbers and I got it to look how I wanted. You can close this if you don't want to leave it as a reminder.
