### ISSUE TITLE
[Suggestion]: Add Trump Gothic Pro Font

### ISSUE THREAD

**Issue by natyusha** [Zeffuro/ZeffUI#79]
### What's your suggestion?

With FFXIV's 6.2 patch adding large recast timer text it would be nice to include the same font that the game uses.

![27bd3bc448b9208f4bd67a94f37d9ee6a81f96e0_41](https://user-images.githubusercontent.com/985941/185826712-bb2690a6-6476-44d1-91f8-14f10baf46a9.png)

I didn't open a pr for this as I'm not sure how the licensing works for these fonts but I will leave a link to a selection of FFXIV's fonts (including TrumpGothicPro) below.

[FFXIV-Fonts](https://cdn.discordapp.com/attachments/266551282733416448/899915892895404042/ffxiv-fonts.zip)

**Comment by Zeffuro** [comment]
I can't officially do this because it's a paid font and I'm not allowed to include it in the repo license wise
I believe there was an easy way to do this in CSS but it may be in one of the Chinese forks that has an example of how to do it in the CSS.

**Comment by natyusha** [comment]
Thanks for the response and ya I figured as much.

For anyone who happens to use the font unofficially I find that a simple drop shadow should be enough to mimic the styling.

`.ability-text{text-shadow: -1px 0 2px #000, 0 1px 2px #000, 1px 0 2px #000, 0 -1px 2px #000}`
