### ISSUE TITLE
[Suggestion]: Hide pull timer if countdown cancelled

### ISSUE THREAD

**Issue by sicmunkychamber** [Zeffuro/ZeffUI#80]
### What's your suggestion?

Currently if a countdown is started the pull timer remains visible and counts down even if the countdown is cancelled early. It'd be nice if the pull timer went invisible in this case.

**Comment by Zeffuro** [comment]
Implemented, thanks for the suggestion!

**Comment by sicmunkychamber** [comment]
Awesome! No more early pull mishaps for me hopefully :)
