### ISSUE TITLE
[Suggestion]: Tempera Coat not an available cooldown to add to custom cooldowns

### ISSUE THREAD

**Issue by Tazus-1** [Zeffuro/ZeffUI#88]
### What's your suggestion?

tempura coat is not an available cooldown that we can add under the custom cooldown section. If it does happen to be possible, it would be awesome if it could be added, as I have not personally found it in the abilities that can be searched for.

Much love for upkeeping this amazing Plugin :D

**Comment by Zeffuro** [comment]
Ah I think something weird is going on with custom cooldown searching, might be xivapi changes. I'll look into it indepth more tonight/tomorrow.

**Comment by Zeffuro** [comment]
Okay I worked on it and you should be able to find it now. 
One warning with that specific ability, you'll have to choose if you use 120s, 90s or 60s cooldown on this. I don't have a reliable way to know if your shield is fully absorbed so this specific cooldown might be a bit janky. But custom cooldowns as a whole should work again.

**Comment by Tazus-1** [comment]
thank you!! Much appreciated :D
